const express = require('express');
const router = express.Router();
const Marcas = require("../models/model-marcas");

router.get("/", async (req, res) => {
    const marcas = await Marcas.find()
    res.json(marcas);
  });


router.get("/all", async (req, res) => {
    const marcas = await Marcas.find({}, {nombre: true, _id:false})
    const nombresMarcas = []
    marcas.map(marca => nombresMarcas.push(marca.nombre));
    res.json(nombresMarcas);
  });

router.get("/modelos/:id", async (req, res) => {
    const marcas = await Marcas.find({nombre: `${req.params.id}`});
    res.json(marcas[0].modelos);
  });


// router.post("/addmany", async (req, res, next)=>{
//     Marcas.insertMany([

//         {
            
//             "id" : 1,
//             "nombre" : "Audi",
//             "modelos" : [ 
//                 "A5", 
//                 "A3", 
//                 "A4", 
//                 "A6", 
//                 "S3", 
//                 "S4", 
//                 "TT", 
//                 "A1", 
//                 "TTS", 
//                 "A1 1.4 T", 
//                 "Q7", 
//                 "Q5", 
//                 "Q3", 
//                 "Q2"
//             ]
//         },
//         {
            
//             "id" : 2,
//             "nombre" : "BMW",
//             "modelos" : [ 
//                 "Serie 6", 
//                 "Serie 7", 
//                 "Z4", 
//                 "M6", 
//                 "Serie 1", 
//                 "Serie 3", 
//                 "Serie 5", 
//                 "Serie 8", 
//                 "1800", 
//                 "M", 
//                 "Serie 4", 
//                 "Serie 2", 
//                 "M235", 
//                 "428i", 
//                 "i", 
//                 "1M", 
//                 "M4", 
//                 "M3", 
//                 "M2", 
//                 "X6", 
//                 "X1", 
//                 "X3", 
//                 "X5", 
//                 "X4", 
//                 "X2"
//             ]
//         },
//         {
        
//             "id" : 3,
//             "nombre" : "Chevrolet",
//             "modelos" : [ 
//                 "Alto", 
//                 "Astra", 
//                 "Bel Air", 
//                 "Camaro", 
//                 "Aveo", 
//                 "Cavalier", 
//                 "Celebrity", 
//                 "Citation", 
//                 "Corsa", 
//                 "Chevy", 
//                 "Epica", 
//                 "Esteem", 
//                 "Impala", 
//                 "Malibu", 
//                 "Monza", 
//                 "Optra", 
//                 "Spark", 
//                 "Sprint", 
//                 "Style", 
//                 "Line", 
//                 "Swift", 
//                 "Wagon R+", 
//                 "Sail", 
//                 "Buick", 
//                 "Cruze", 
//                 "39", 
//                 "Cobalt", 
//                 "Sonic", 
//                 "Onix", 
//                 "Beat", 
//                 "Vivant", 
//                 "Blazer 4x2", 
//                 "Captiva", 
//                 "Tahoe", 
//                 "HHR", 
//                 "Courier", 
//                 "Zafira", 
//                 "Blazer", 
//                 "4x4", 
//                 "Grand", 
//                 "Vitara", 
//                 "Grand Blazer", 
//                 "Rodeo", 
//                 "Suburban", 
//                 "Trail", 
//                 "Blazer", 
//                 "Traverse", 
//                 "Orlando", 
//                 "Tracker", 
//                 "Equinox", 
//                 "Jimny", 
//                 "Samurai", 
//                 "Trooper", 
//                 "Vitara", 
//                 "FSR", 
//                 "FVR", 
//                 "FTR", 
//                 "NNR", 
//                 "Cheyenne", 
//                 "C30", 
//                 "3100", 
//                 "Luv", 
//                 "Brigadier", 
//                 "C70", 
//                 "Carry", 
//                 "NHR", 
//                 "NPR", 
//                 "NKR", 
//                 "Super", 
//                 "Brigadier", 
//                 "Super", 
//                 "Carry", 
//                 "Kodiak", 
//                 "NQR", 
//                 "FRR", 
//                 "FVZ", 
//                 "N300", 
//                 "Luv", 
//                 "D-max", 
//                 "DMAX", 
//                 "Super", 
//                 "Carry", 
//                 "NQR", 
//                 "FRR", 
//                 "Carry", 
//                 "CHR", 
//                 "LV", 
//                 "NKR", 
//                 "NPR", 
//                 "Luv", 
//                 "D-max", 
//                 "SSR", 
//                 "Luv Dmax", 
//                 "N300", 
//                 "Apache", 
//                 "C10", 
//                 "C30", 
//                 "Cheyenne", 
//                 "Luv 1.6", 
//                 "Luv 2.2", 
//                 "Luv 2.3", 
//                 "Luv 2.5", 
//                 "Colorado", 
//                 "Luv 2.8", 
//                 "Silverado", 
//                 "Optra", 
//                 "Spark", 
//                 "Corsa", 
//                 "Taxi", 
//                 "Chevette", 
//                 "Chevytaxi", 
//                 "7:24", 
//                 "ChevyVan", 
//                 "ChevyWagon", 
//                 "Super", 
//                 "Carry", 
//                 "N200", 
//                 "N300"
//             ]
//         },
//         {
            
//             "id" : 4,
//             "nombre" : "Citroen",
//             "modelos" : [ 
//                 "Xsara", 
//                 "Picasso", 
//                 "C3", 
//                 "C5", 
//                 "Saxo", 
//                 "Xantia", 
//                 "ZX", 
//                 "C4", 
//                 "C2", 
//                 "Xsara", 
//                 "DS3", 
//                 "DS4", 
//                 "DS5", 
//                 "C-Elysee", 
//                 "Aircross", 
//                 "Aircross", 
//                 "C4", 
//                 "C3", 
//                 "Berlingo", 
//                 "Jumper", 
//                 "Jumpy", 
//                 "Berlingo"
//             ]
//         },

//         {
    
//     "id" : 5,
//     "nombre" : "Daihatsu",
//     "modelos" : [ 
//         "Charade", 
//         "Charmant", 
//         "Sirion", 
//         "Materia", 
//         "Terios", 
//         "F20", 
//         "Feroza", 
//         "Rocky", 
//         "Delta", 
//         "V126"
//     ]
// },
// {

//     "id" : 6,
//     "nombre" : "Dodge",
//     "modelos" : [ 
//         "Coronet", 
//         "Dart", 
//         "Demon", 
//         "D100", 
//         "Royal", 
//         "Journey", 
//         "Caliber", 
//         "Fargo", 
//         "Durango", 
//         "300", 
//         "600", 
//         "900", 
//         "500", 
//         "Ram", 
//         "D100", 
//         "Dakota", 
//         "Caravan"
//     ]
// },
// {
  
//     "id" : 7,
//     "nombre" : "Fiat",
//     "modelos" : [ 
//         "Zastava", 
//         "Idea", 
//         "124", 
//         "Punto", 
//         "147", 
//         "Palio", 
//         "Polsky", 
//         "Premio", 
//         "Siena", 
//         "Stilo", 
//         "Tipo", 
//         "Topolino", 
//         "Uno", 
//         "500", 
//         "Linea", 
//         "Nuevo", 
//         "Palio", 
//         "Argo", 
//         "Cronos", 
//         "Adventure", 
//         "500", 
//         "X", 
//         "Fiorino", 
//         "Furgon", 
//         "Strada", 
//         "Idea"
//     ]
// },
// {
    
//     "id" : 8,
//     "nombre" : "Ford",
//     "modelos" : [ 
//         "Fusion", 
//         "Crown", 
//         "Victoria", 
//         "Falcon", 
//         "Festiva", 
//         "Fiesta", 
//         "Focus", 
//         "Granada", 
//         "Laser", 
//         "Mustang", 
//         "Taurus", 
//         "Hot", 
//         "Rod", 
//         "Escort", 
//         "Ltd", 
//         "555E", 
//         "Chiva", 
//         "Ecosport", 
//         "Panel", 
//         "Edge", 
//         "Flex", 
//         "Courier", 
//         "Escape", 
//         "Expedition", 
//         "Explorer", 
//         "Llanero", 
//         "Bronco", 
//         "Piragua", 
//         "Aeromax", 
//         "Cargo", 
//         "815", 
//         "F350", 
//         "600", 
//         "F8000", 
//         "F 600", 
//         "F 350[7]", 
//         "F9000", 
//         "F-150", 
//         "Cargo 1019", 
//         "Cargo 816", 
//         "F250", 
//         "Nueva", 
//         "Ranger", 
//         "Explorer", 
//         "F100", 
//         "F-150", 
//         "F350", 
//         "Ranger"
//     ]
// },
// {

//     "id" : 9,
//     "nombre" : "Honda",
//     "modelos" : [ 
//         "Accord", 
//         "Civic", 
//         "CRX", 
//         "Fit", 
//         "Integra", 
//         "Legend", 
//         "Prelude", 
//         "CR-V", 
//         "Pilot", 
//         "Hr-v", 
//         "WRV", 
//         "Ridgeline", 
//         "Odyssey"
//     ]
// },
// {
   
//     "id" : 10,
//     "nombre" : "Hyundai",
//     "modelos" : [ 
//         "Elantra Supreme", 
//         "i30", 
//         "Genesis", 
//         "Accent", 
//         "Atos", 
//         "Elantra", 
//         "Excel", 
//         "Getz", 
//         "Veloster", 
//         "New Elantra", 
//         "Santro", 
//         "Sonata", 
//         "Tiburon", 
//         "I45", 
//         "i25 Accent", 
//         "i35", 
//         "i25", 
//         "Veloster", 
//         "Equus", 
//         "Azera", 
//         "i40", 
//         "EON", 
//         "Grand i10 Illusion", 
//         "Grand i10", 
//         "i20", 
//         "Ioniq", 
//         "Tucson", 
//         "Veracruz", 
//         "Santafe", 
//         "Terracan", 
//         "Creta", 
//         "HD 1000", 
//         "HD 270", 
//         "Porter", 
//         "Starex", 
//         "HD 120", 
//         "170", 
//         "H100", 
//         "HD72", 
//         "HD78", 
//         "HD65", 
//         "H1", 
//         " Grand Starex", 
//         "County", 
//         "Aerocity", 
//         "Grace", 
//         "Vision", 
//         "Grand City Taxi", 
//         "Grand Pony Taxi", 
//         "Grand I10", 
//         "Gyro", 
//         "Grand Metro Taxi", 
//         "City Taxi", 
//         "Santamo"
//     ]
// },
// {
    
//     "id" : 11 ,
//     "nombre" : "Jeep",
//     "modelos" : [ 
//         "Compass", 
//         "Patriot", 
//         "Commander", 
//         "Cherokee", 
//         "Grand Cherokee", 
//         "Wagoneer", 
//         "Grand Wagoneer", 
//         "Renegade", 
//         "Willys", 
//         "Liberty", 
//         "CJ5", 
//         "CJ6", 
//         "CJ7", 
//         "Comando", 
//         "Scrambler", 
//         "Wrangler", 
//         "New Compass"
//     ]
// },
// {
//     "id" : 12,
//     "nombre" : "Kia",
//     "modelos" : [ 
//         "Rio Xcite", 
//         "New Rio", 
//         "Rio Stylus", 
//         "Cadenza", 
//         "Cerato", 
//         "Picanto", 
//         "Pride", 
//         "Rio", 
//         "Sephia", 
//         "Spectra", 
//         "Optima", 
//         "Rio Spice", 
//         "Picanto iON", 
//         "Quoris", 
//         "Cerato Forte", 
//         "Cerato Koup", 
//         "Cerato Pro", 
//         "Tonic", 
//         "Cerato Vivro", 
//         "Stinger", 
//         "Carens", 
//         "Sedona", 
//         "Mohave", 
//         "Carens Rondo", 
//         "Soul", 
//         "Sportage Revolution", 
//         "Grand Sportage", 
//         "Sorento", 
//         "Sportage", 
//         "Sportage FQ", 
//         "Sorento Radical", 
//         "Niro", 
//         "Tonic", 
//         "Ceres", 
//         "K 2400", 
//         "K 2700", 
//         "K 3000S", 
//         "Carnival", 
//         "Pregio", 
//         "Grand Pregio", 
//         "Picanto", 
//         "Eko", 
//         "Grand Sephia", 
//         "Super Eko", 
//         "Ekotaxi", 
//         "Grand Ekotaxi", 
//         "Carnival", 
//         "Pregio"
//     ]
// },
// {
    
//     "id" : 13,
//     "nombre" : "Mazda",
//     "modelos" : [ 
//         "Speed 3", 
//         "2", 
//         "3 All New", 
//         "121", 
//         "3", 
//         "6", 
//         "626", 
//         "Allegro", 
//         "Demio", 
//         "Matsuri 625", 
//         "MX5", 
//         "323", 
//         "MX-5 Miata", 
//         " CX-5", 
//         "5", 
//         "CX-7", 
//         "CX-9", 
//         "MPV", 
//         "Tribute", 
//         "CX-3", 
//         "T", 
//         "T45", 
//         "BT-50", 
//         "B2200", 
//         "B2000", 
//         "B1600", 
//         "B2600", 
//         "323"
//     ]
// },
// {
    
//     "id" : 14,
//     "nombre" : "Mitsubichi",
//     "modelos" : [ 
//         "Colt", 
//         "Eclipse", 
//         "Galant", 
//         "Lancer", 
//         "New Lancer", 
//         "Mirage", 
//         "New Outlander", 
//         "Pajero", 
//         "Endeavor", 
//         "ASX", 
//         "Nativa", 
//         "Outlander", 
//         "LO42", 
//         "Montero", 
//         "New Montero", 
//         "New Nativa", 
//         "Outlander", 
//         "New Outlander", 
//         "WAGON", 
//         "L200", 
//         "Fuso", 
//         "Canter", 
//         "L300", 
//         "Sportero", 
//         "L200", 
//         "Expo", 
//         "L300", 
//         "Space Wagon"
//     ]
// },
// {
//     "id" : 15,
//     "nombre" : "Nissan",
//     "modelos" : [ 
//         "Tiida", 
//         "Micra", 
//         "Datsun", 
//         "March", 
//         "280Z", 
//         "370Z", 
//         "350z", 
//         "AD Wagon", 
//         "Almera", 
//         "Altima", 
//         "Bluebird", 
//         "Maxima", 
//         "Primera", 
//         "Sentra", 
//         "Sunny", 
//         "Versa", 
//         "Note", 
//         "New Sentra", 
//         "New March", 
//         "New Versa", 
//         "Leaf", 
//         "New", 
//         "Pathfinder", 
//         "Patrol", 
//         "X-trail", 
//         "I Qashqai", 
//         "Quest", 
//         "Armada", 
//         "Murano", 
//         "Pathfinder", 
//         "X-Trail", 
//         "Terrano II", 
//         "Nuevo Patrol", 
//         "Juke", 
//         "Qashqai 2", 
//         "X-trail Classic", 
//         "New Qashqai", 
//         "Kicks", 
//         "MT3000", 
//         "U41", 
//         "Cabstar", 
//         "Urvan", 
//         "TK55", 
//         "Montacarga", 
//         "D22 Frontier", 
//         "Chasis", 
//         "Frontier", 
//         "Navara", 
//         " Frontier NP300", 
//         "Titan", 
//         "Frontier", 
//         "NP 300", 
//         "Tl720", 
//         "D21", 
//         "D22", 
//         "Quest", 
//         "Vanette"
//     ]
// },
// {
//     "id" : 16,
//     "nombre" : "Renault",
//     "modelos" : [ 
//         "Megane II", 
//         "Logan", 
//         "Sandero", 
//         "Symbol", 
//         "II", 
//         "Stepway", 
//         "Scala", 
//         "r12", 
//         "r18", 
//         "r19", 
//         "r21", 
//         "r4", 
//         "r6", 
//         "r9", 
//         "Clio", 
//         "Etoile", 
//         "Laguna", 
//         "Megane", 
//         "Scenic", 
//         "Symbol", 
//         "Twingo", 
//         "Fluence", 
//         "Megane III", 
//         "Nuevo Twingo", 
//         "Twizy", 
//         "Zoe", 
//         "Kwid", 
//         "Grand Scenic II", 
//         "Koleos", 
//         "Duster", 
//         "Nueva Koleos", 
//         "Stepway", 
//         "Captur", 
//         "Midlum 270.18", 
//         "Kerax 320.28", 
//         "Master", 
//         "Trafic", 
//         "Kangoo", 
//         "Nueva Master", 
//         "Trafic", 
//         "Duster Oroch", 
//         "Alaskan", 
//         "Citius", 
//         "Symbol", 
//         "Logan"
//     ]
// },
// {
//     "id" : 17,
//     "nombre" : "Toyota",
//     "modelos" : [ 
//         "Supra", 
//         "Camry", 
//         "Celica", 
//         "Corolla", 
//         "Corona", 
//         "Crown", 
//         "Tercel", 
//         "Yaris", 
//         "Prius", 
//         "Previa", 
//         "Rav 4", 
//         "Sequoia", 
//         "Highlander", 
//         "FJ Cruiser", 
//         "Land Cruiser", 
//         "Fortuner", 
//         "4Runner", 
//         "Burbuja", 
//         "Prado", 
//         "Hilux", 
//         "SW4", 
//         "Rush", 
//         "FJ70", 
//         "FJ40", 
//         "FJ43", 
//         "FJ", 
//         "Land Cruiser 200", 
//         "Sumo", 
//         "Montacarga", 
//         "Tundra", 
//         "Tacoma", 
//         "Hilux", 
//         "Sienna"
//     ]
// },
// {
//     "id" : 17,
//     "nombre" : "Volkswagen",
//     "modelos" : [ 
//         "Bora", 
//         "Nuevo Jetta", 
//         "Escarabajo", 
//         "Fastback", 
//         "Fox", 
//         "Gol", 
//         "Golf", 
//         "Jetta", 
//         "New Beetle", 
//         "Parati", 
//         "Passat", 
//         "Polo", 
//         "Scirocco", 
//         "Variant", 
//         "Vento", 
//         "Voyage", 
//         "Buggy", 
//         "Beetle", 
//         "Cross Up", 
//         "Virtus", 
//         "Touareg", 
//         "Space Fox", 
//         "Tiguan", 
//         "Crossfox", 
//         "Worker", 
//         "Transporter", 
//         "9-150", 
//         "Crafter", 
//         "Delivery", 
//         "Constellation", 
//         "Crafter 50", 
//         "Transporter", 
//         "LT 35", 
//         "LT 46", 
//         "Volksbus", 
//         "Saveiro", 
//         "Amarok", 
//         "Kombi", 
//         "Crafter 35"
//     ]
// }

//     ])
//     res.json({archived:true})
// })

module.exports = router